### ISSUE TITLE
Add a placeholder tilemap/atlas (+Create placeholder art for this. It's gonna be bad.)

### ISSUE THREAD

**Issue by OpenGameLab** [OpenGameLab/Firechucking#5]
Quick and dirty tilemap atlas. (Placeholder assets)

We need : 

- Grass tile (destructible) 
- Stone tile (non-destructible)
- One-way Platforming tiles (destructible/not?)
- Traversal tiles (At least one "Laddder" for UP and maybe a "pole" for DOWN?) ** Zipline, if we're feeling ambitious.
- Variable/timer tracking for destroyed tiles to "regenerate" / handle tiles being attacked while destroyed.

**Comment by DenBread** [comment]
Ok

**Comment by OpenGameLab** [comment]
All done except the variable/timer for tracking destroyed tiles. This will be its own issue/goal.
